// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8RmeivwnpUMULOkt64cVZJ9gPN3YQQCo',
    appId: '1:523530378217:web:d65b04f78fc5eecd51c978',
    messagingSenderId: '523530378217',
    projectId: 'my-ecommerce-app-9ac51',
    authDomain: 'my-ecommerce-app-9ac51.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-9ac51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwEMs87BvAquUkygNiBLPqsr8Nx1q31T4',
    appId: '1:523530378217:android:7f2932b61c67992251c978',
    messagingSenderId: '523530378217',
    projectId: 'my-ecommerce-app-9ac51',
    storageBucket: 'my-ecommerce-app-9ac51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoodij3eG1otYFP2QC9WvwDqjokJ8OG_4',
    appId: '1:523530378217:ios:09718100a4cb4d2b51c978',
    messagingSenderId: '523530378217',
    projectId: 'my-ecommerce-app-9ac51',
    storageBucket: 'my-ecommerce-app-9ac51.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoodij3eG1otYFP2QC9WvwDqjokJ8OG_4',
    appId: '1:523530378217:ios:09718100a4cb4d2b51c978',
    messagingSenderId: '523530378217',
    projectId: 'my-ecommerce-app-9ac51',
    storageBucket: 'my-ecommerce-app-9ac51.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8RmeivwnpUMULOkt64cVZJ9gPN3YQQCo',
    appId: '1:523530378217:web:a0b1e9cf7558490851c978',
    messagingSenderId: '523530378217',
    projectId: 'my-ecommerce-app-9ac51',
    authDomain: 'my-ecommerce-app-9ac51.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-9ac51.firebasestorage.app',
  );
}
